[project]
name = "broken"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mypy>=1.18.2",
    "types-protobuf>=6.32.1.20251105",
]
